# Generated by Django 4.2.6 on 2023-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=10000, unique=True)),
                ('short_url', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
